version: 2
jobs:
build:
working_directory: ~/spring-recipe-app
docker:
  # specify the version you desire here
  - image: circleci/openjdk:8-jdk
steps:
  - checkout
  # Download and cache dependencies
  - restore_cache:
key: spring5-recipe-app-{‌{ checksum "pom.xml" }}
       - run: mvn install -DskipTests
       - run: mvn dependency:go-offline
       - save_cache:
paths:
  - ~/.m2